# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "School Incident",
    "version": "14.0.1.2.2",
    "website": "https://simetri-sinergi.id",
    # pylint: disable=line-too-long
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia, Odoo Community Association (OCA)",  # noqa: B950
    # pylint: enable=line-too-long
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_school",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_localdict_mixin",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/res_groups/school_academic_alert.xml",
        "security/res_groups/school_incident_weekly_review.xml",
        "security/ir_model_access/school_incident_type.xml",
        "security/ir_model_access/school_incident_escalation_criteria.xml",
        "security/ir_model_access/school_academic_alert_level.xml",
        "security/ir_model_access/school_incident.xml",
        "security/ir_model_access/school_incident_parent_contact.xml",
        "security/ir_model_access/escalate_incident.xml",
        "security/ir_model_access/school_academic_alert.xml",
        "security/ir_model_access/school_incident_weekly_review.xml",
        "security/ir_rule/school_incident.xml",
        "security/ir_rule/school_academic_alert.xml",
        "security/ir_rule/school_incident_weekly_review.xml",
        "ir_sequence/school_incident.xml",
        "ir_sequence/school_academic_alert.xml",
        "ir_sequence/school_incident_weekly_review.xml",
        "sequence_template/school_incident.xml",
        "sequence_template/school_academic_alert.xml",
        "sequence_template/school_incident_weekly_review.xml",
        "approval_template/school_incident.xml",
        "approval_template/school_academic_alert.xml",
        "approval_template/school_incident_weekly_review.xml",
        "policy_template/school_incident.xml",
        "policy_template/school_academic_alert.xml",
        "policy_template/school_incident_weekly_review.xml",
        "data/school_incident_type_academic.xml",
        "data/school_academic_alert_level_data.xml",
        "menu.xml",
        "views/school_incident_type.xml",
        "views/school_incident_escalation_criteria.xml",
        "views/school_academic_alert_level.xml",
        "wizards/escalate_incident.xml",
        "views/school_incident.xml",
        "views/school_academic_alert.xml",
        "views/school_incident_weekly_review.xml",
    ],
}
